component: http
name: chronus-backend
stage: prod
inputs:
  name: ${name}-${stage}-${app}
  src:
    src: ./
    exclude:
      - .env
  region: ap-shanghai
  faas:
    runtime: Nodejs12.16
    framework: egg
    name: '${name}'
  apigw:
    protocols:
      - http
      - https
    environment: release
  functionConf: # 函数配置相关
    timeout: 10 # 超时时间，单位秒
    memorySize: 128 # 内存大小，单位MB
    environment: #  环境变量
      variables: #  环境变量数组
        NODE_ENV: ${stage}
app: chronus