component: http
name: chronus-backend
stage: dev
inputs:
  name: ${name}-${stage}-${app}
  src:
    src: ./
    exclude:
      - .env
  faas:
    region: ap-shanghai
    runtime: Nodejs12.16
    framework: egg
    name: '${name}'
  apigw:
    protocols:
      - http
      - https
    environment: release
app: chronus
